name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        jit: [1205, 1254, 0]
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 8.0.2
          ini-values: opcache.enable_cli=1, opcache.jit=${{ matrix.jit }}, opcache.jit_buffer_size=8M
          extensions: :xdebug

      - name: Run test scripts
        run: |
                STATUS=0
                for i in $(ls samples); do
                        php samples/$i
                        EXITCODE=$?
                        if [[ $EXITCODE -ne 0 ]]; then
                                echo "FAILED TEST $i with code $EXITCODE"
                                STATUS=1
                        else
                                echo "PASSED TEST $i"
                        fi
                done
                exit $STATUS
